export interface WsApi {
  listAgents: () => Promise<any>;
  listAllAgents: () => Promise<any>;
  getAgent: (id: string) => Promise<any>;
  createAgent: (data: unknown) => Promise<any>;
  updateAgent: (id: string, data: unknown) => Promise<any>;
  deleteAgent: (id: string) => Promise<any>;
  updateAgentTemplate: (id: string, templateId: string | null) => Promise<any>;
  updateAgentMcpConfigPath: (id: string, mcpConfigPath: string | null) => Promise<any>;
  listTemplates: () => Promise<any[]>;
  listSkills: () => Promise<any>;
  getSkill: (id: string) => Promise<any>;
  createSkill: (data: unknown) => Promise<any>;
  updateSkill: (id: string, data: unknown) => Promise<any>;
  deleteSkill: (id: string) => Promise<any>;
  addSkillTag: (skillId: string, tag: string) => Promise<any>;
  removeSkillTag: (skillId: string, tag: string) => Promise<any>;
  scanSkills: () => Promise<any>;
  applySkill: (skillId: string, agentId: string) => Promise<any>;
  unapplySkill: (skillId: string, agentId: string) => Promise<any>;
  getAppliedAgentsForSkill: (skillId: string) => Promise<any>;
  importScannedSkills: (skills: unknown[]) => Promise<any>;
  checkSkillConsistency: () => Promise<any>;
  fixSkillConsistency: () => Promise<any>;
  importSkillFromLocal: (sourcePath: string, name: string) => Promise<any>;
  importSkillFromArchive: (archivePath: string, name: string) => Promise<any>;
  searchSkillDiscovery: (providerId: string, query: string) => Promise<any>;
  installSkillDiscovery: (providerId: string, name: string, source: string) => Promise<any>;
  listSkillProviders: () => Promise<{ id: string; name: string; description: string; inputPlaceholder: string }[]>;
  openDirectoryDialog: () => Promise<{ canceled: boolean; path: string | null }>;
  openFileDialog: () => Promise<{ canceled: boolean; path: string | null }>;
  listMcps: () => Promise<any>;
  getMcp: (id: string) => Promise<any>;
  createMcp: (data: unknown) => Promise<any>;
  updateMcp: (id: string, data: unknown) => Promise<any>;
  deleteMcp: (id: string) => Promise<any>;
  addMcpTag: (mcpId: string, tag: string) => Promise<any>;
  removeMcpTag: (mcpId: string, tag: string) => Promise<any>;
  scanMcps: () => Promise<any>;
  applyMcp: (mcpId: string, agentId: string) => Promise<any>;
  unapplyMcp: (mcpId: string, agentId: string) => Promise<any>;
  syncMcp: (mcpId: string) => Promise<any>;
  previewMcpApply: (mcpId: string, agentId: string) => Promise<any>;
  getAppliedAgentsForMcp: (mcpId: string) => Promise<any>;
  importScannedMcps: (mcps: unknown[]) => Promise<any>;
  checkMcpConsistency: () => Promise<any>;
  fixMcpConsistency: () => Promise<any>;
  testMcp: (mcpId: string) => Promise<any>;
  batchTestMcps: () => Promise<any>;
  callMcpTool: (mcpId: string, toolName: string, args: Record<string, unknown>) => Promise<any>;
  getMcpTools: (mcpId: string) => Promise<any[]>;
  getMcpPrompts: (mcpId: string) => Promise<any[]>;
  getMcpTestResult: (mcpId: string) => Promise<any>;
  isKeychainAvailable: () => Promise<boolean>;
  storeSecret: (mcpName: string, varName: string, value: string) => Promise<any>;
  deleteSecret: (mcpName: string, varName: string) => Promise<any>;
  onBatchTestProgress: (callback: (progress: any) => void) => void;
  onBatchTestResult: (callback: (result: any) => void) => void;
  removeBatchTestListeners: () => void;
  listProviders: () => Promise<any>;
  getProvider: (id: string) => Promise<any>;
  createProvider: (data: unknown) => Promise<any>;
  updateProvider: (id: string, data: unknown) => Promise<any>;
  deleteProvider: (id: string) => Promise<any>;
  setProviderApiKey: (providerName: string, apiKey: string) => Promise<any>;
  getProviderApiKey: (providerName: string) => Promise<any>;
  isKeytarSupported: () => Promise<any>;
  listTags: () => Promise<any>;
  createTag: (data: unknown) => Promise<any>;
  renameTag: (id: string, name: string) => Promise<any>;
  deleteTag: (id: string) => Promise<any>;
  search: (query: string) => Promise<any>;

  // Projects
  projectList: (search?: string) => Promise<any>;
  projectGet: (id: string) => Promise<any>;
  projectCreate: (data: unknown) => Promise<any>;
  projectUpdate: (id: string, data: unknown) => Promise<any>;
  projectDelete: (id: string) => Promise<any>;
  projectToggleAgent: (projectId: string, agentId: string, enabled: boolean) => Promise<any>;
  projectSkillList: (projectId: string) => Promise<any>;
  projectApplySkill: (projectId: string, skillId: string, agentId: string) => Promise<any>;
  projectUnapplySkill: (projectId: string, skillId: string, agentId: string) => Promise<any>;
  projectAvailableSkills: (projectId: string, agentId?: string) => Promise<any>;
  projectMcpList: (projectId: string) => Promise<any>;
  projectApplyMcp: (projectId: string, mcpName: string, agentId: string) => Promise<any>;
  projectUnapplyMcp: (projectId: string, mcpName: string, agentId: string) => Promise<any>;
  projectAvailableMcps: (projectId: string, agentId?: string) => Promise<any>;
  projectScanSkills: (projectId: string) => Promise<any>;
  projectScanMcps: (projectId: string) => Promise<any>;
  projectImportScannedSkills: (skills: unknown[]) => Promise<any>;
  projectImportScannedMcps: (mcps: unknown[]) => Promise<any>;

  // Logger
  getLogPath: () => Promise<string | null>;
  setDebugMode: (enabled: boolean) => Promise<void>;
  isDebugMode: () => Promise<boolean>;

  // App settings
  getSetting: (key: string) => Promise<string | null>;
  setSetting: (key: string, value: string) => Promise<void>;
}
